import type { AdvertiserAsset } from '@/types'

export const MOCK_ADVERTISERS: AdvertiserAsset[] = [
  {
    id: 'beverage-zero-soda',
    industry: '饮料食品',
    brandName: '清醒气泡',
    productName: '0 糖 0 脂气泡水',
    sourceMaterial: '主视觉为冰块、气泡、水珠和清爽开瓶声，原始卖点是解腻、低负担、年轻活力。',
    keySellingPoint: '0糖0脂，清爽解腻，适合战斗/运动/美食后的轻负担补水场景',
    targetAudience: '18-35岁年轻用户、追剧用户、轻健康人群',
    brandTone: '清爽、现代、轻松、活力',
    bannedWords: '最好、第一、绝对、治愈、减肥',
    suitableScenes: ['美食', '运动', '战后休息', '转场', '炎热户外', '轻松对白'],
    suitableFormats: ['short', 'buffer-card', 'interactive'],
    budgetTier: 'medium',
  },
  {
    id: 'beauty-peach-makeup',
    industry: '美妆护肤',
    brandName: '花间色',
    productName: '桃花妆口红套装',
    sourceMaterial: '原始素材包含桃花色口红、古风花瓣、妆容前后对比和随身补妆镜头。',
    keySellingPoint: '自然桃花色，适合日常通勤与古风妆容灵感迁移',
    targetAudience: '18-32岁女性用户、古装剧/穿搭/美妆兴趣用户',
    brandTone: '精致、柔和、东方美学、灵感感',
    bannedWords: '医美、永久、最显白、必买',
    suitableScenes: ['古装', '梳妆', '女性角色', '宫廷', '约会', '穿搭'],
    suitableFormats: ['character-match', 'interactive', 'buffer-card'],
    budgetTier: 'medium',
  },
  {
    id: 'game-mystery-room',
    industry: '游戏娱乐',
    brandName: '暗门档案',
    productName: '密室推理手游',
    sourceMaterial: '原始素材包含密室门锁、线索板、倒计时、玩家协作推理和悬疑氛围音乐。',
    keySellingPoint: '3分钟一局，沉浸式推理，和朋友一起破解谜案',
    targetAudience: '悬疑剧、推理、密室逃脱、轻度游戏用户',
    brandTone: '悬疑、聪明、紧张但不恐怖',
    bannedWords: '赌博、赢钱、恐吓、血腥',
    suitableScenes: ['悬疑', '转场', '线索发现', '案件复盘', '夜景', '高张力后缓冲'],
    suitableFormats: ['buffer-card', 'interactive', 'drama-style'],
    budgetTier: 'high',
  },
  {
    id: 'ecommerce-style-sale',
    industry: '电商优惠',
    brandName: '灵感好物节',
    productName: '角色同款穿搭会场',
    sourceMaterial: '原始素材为服饰、家居、数码好物合集，强调同款灵感、限时券和一键收藏。',
    keySellingPoint: '从剧情同款灵感出发，快速找到相似穿搭/家居/数码好物',
    targetAudience: '喜欢种草、穿搭、家居、数码和电商优惠的追剧用户',
    brandTone: '实用、轻松、种草、不强推',
    bannedWords: '最低价、全网第一、稳赚',
    suitableScenes: ['都市', '家居', '穿搭', '办公室', '约会', '生活方式'],
    suitableFormats: ['character-match', 'interactive', 'end-card'],
    budgetTier: 'medium',
  },
  {
    id: 'auto-city-ev',
    industry: '汽车出行',
    brandName: '星驰 EV',
    productName: '城市智能电动 SUV',
    sourceMaterial: '原始素材包括夜间城市道路、智能座舱、家庭出行和长续航卖点。',
    keySellingPoint: '长续航、智能辅助驾驶、适合城市通勤和周末出游',
    targetAudience: '25-45岁城市家庭、通勤用户、科技兴趣用户',
    brandTone: '可靠、科技、舒适、高级',
    bannedWords: '自动驾驶无风险、绝对安全、最强',
    suitableScenes: ['城市', '公路', '家庭', '旅行', '追逐后缓冲', '片尾'],
    suitableFormats: ['drama-style', 'end-card', 'short'],
    budgetTier: 'high',
  },
  {
    id: 'travel-ancient-city',
    industry: '旅游酒店',
    brandName: '山海行旅',
    productName: '古城周末旅行套餐',
    sourceMaterial: '原始素材包含古城夜景、客栈、茶馆、汉服体验、两天一夜路线。',
    keySellingPoint: '低门槛周末短途旅行，把剧里的古风氛围带进现实',
    targetAudience: '古装剧、旅行、拍照打卡、情侣/朋友出游用户',
    brandTone: '诗意、松弛、向往、沉浸',
    bannedWords: '最低价、唯一、包治愈',
    suitableScenes: ['古装', '空镜', '山水', '城市场景', '片尾', '慢节奏转场'],
    suitableFormats: ['end-card', 'buffer-card', 'drama-style'],
    budgetTier: 'medium',
  },
]
