import type { AdvertiserAsset } from '@/types'

export const MOCK_ADVERTISERS: AdvertiserAsset[] = [
  {
    id: 'beverage-yuanqi-sparkling-water',
    industry: '饮料 / 无糖气泡水',
    brandName: '元气森林',
    productName: '0糖气泡水系列',
    sourceMaterial: '素材来自 demo 广告素材库：気字视觉符号与元气森林 LOGO，大面积留白，低饱和白桃粉/葡萄紫/淡绿，气泡上升、水花溅起、透明玻璃杯、朋友聚会/露营/野餐/夏日泳池边、书桌旁一瓶气泡水和夜晚窗边解压时刻。',
    keySellingPoint: '0糖、0脂、0卡，气更足、击喉感强，满足汽水爽感同时降低负罪感',
    targetAudience: '90后、95后、00后追剧用户，以及关注身材健康但不想牺牲口感的轻养生人群',
    brandTone: '年轻、元气、清新、健康、轻松、生活方式感，兼具小清新与新中式表达',
    bannedWords: '最好、第一、绝对、减肥、喝不胖、治疗、治愈',
    suitableScenes: ['下午茶', '聚会', '通勤', '加班', '健身后', '宅家追剧', '夏日户外', '转场'],
    suitableFormats: ['short', 'buffer-card', 'interactive'],
    budgetTier: 'medium',
    assetVisualElements: ['気字视觉符号', '低饱和白桃粉/葡萄紫/淡绿包装', '气泡上升', '透明玻璃杯', '水珠凝结', '夏日窗边'],
    usageScenarios: ['宅家追剧', '聚会', '露营野餐', '通勤书桌', '夜晚解压', '夏日户外'],
    emotionalMapping: ['清爽', '轻松', '元气', '松弛', '无负担感'],
    cameraSuggestions: ['slow motion bubbles', 'cold condensation macro', 'handheld lifestyle shot', 'glass pour close-up'],
    audioSuggestions: ['开瓶声', '气泡声', '冰块碰杯', '轻快清爽音乐'],
    forbiddenRepresentations: ['不得表现减肥或治疗效果', '不得承诺喝不胖', '不得使用绝对健康承诺'],
    formatFit: {
      'buffer-card': '用气泡、水珠和低饱和色彩做剧情呼吸点，产品作为桌边环境物件短暂出现。',
      short: '用开瓶、倒入玻璃杯和清爽表情构成三镜头短广告。',
      interactive: '围绕“继续沉浸还是清爽一下”设置低打扰选择。',
    },
  },
  {
    id: 'beauty-florasis-lipstick',
    industry: '彩妆 / 国货美妆',
    brandName: '花西子',
    productName: '东方雕花口红',
    sourceMaterial: '素材来自 demo 广告素材库：双鹤 LOGO、圆纹、金色线条，琉璃/玉石/绸缎质感，山水水墨、荷花/牡丹/山茶、古典园林、窗棂、屏风、团扇、发簪，雕花膏体与东方佳人妆面。',
    keySellingPoint: '雕花膏体与东方美学包装，结合花卉精华与国风彩妆体系，兼具妆效、仪式感和送礼收藏价值',
    targetAudience: '20-30岁女性、国风/汉服/古风审美爱好者、小红书抖音美妆内容用户、送礼人群',
    brandTone: '东方雅致、国潮、高级、细腻、仪式感，古典与现代并存',
    bannedWords: '医美、永久、最显白、必买、养肤疗效、唯一',
    suitableScenes: ['古装', '梳妆', '女性角色', '宫廷', '约会', '送礼', '国风', '仪式感'],
    suitableFormats: ['character-match', 'interactive', 'buffer-card'],
    budgetTier: 'medium',
    assetVisualElements: ['双鹤 LOGO', '金色线条管身', '雕花膏体', '琉璃玉石质感', '绸缎布景', '窗棂屏风', '花瓣色彩过渡', '唇部质感特写'],
    usageScenarios: ['梳妆', '约会前', '通勤前', '镜前补妆', '车内补妆', '古装妆容灵感转现实'],
    emotionalMapping: ['温柔', '自信', '东方雅致', '高级', '仪式感'],
    cameraSuggestions: ['macro close-up', 'soft focus', 'mirror reflection', 'slow push-in', 'shallow depth of field'],
    audioSuggestions: ['轻柔布料声', '镜盒开合声', '柔和古筝', '细腻环境音'],
    forbiddenRepresentations: ['不得表现永久改变肤质', '不得承诺医美效果', '不得宣称唯一或必买', '不得冒充原剧官方同款'],
    formatFit: {
      'character-match': '从角色妆造/镜前细节转译到东方雕花口红，用“同款灵感/相似氛围”表达，不说官方同款。',
      'buffer-card': '做成古风梳妆台上的轻量动态卡，低信息密度，花瓣和金线完成转场。',
      interactive: '用“更想看温柔妆感还是英气妆感”做低打扰互动。',
    },
  },
  {
    id: 'sports-nike-running-shoes',
    industry: '运动服饰 / 跑步鞋类',
    brandName: 'Nike',
    productName: '专业跑鞋系列',
    sourceMaterial: '素材来自 demo 广告素材库：Swoosh 标志、Just Do It 精神、赛事号牌、终点线、脚着地瞬间、汗水、肌肉线条、低角度城市天际线/跑道、鞋底纹路与中底结构拆解，黑白搭配荧光绿/亮橙/亮粉。',
    keySellingPoint: '回弹、缓震、支撑与轻质科技，覆盖新手到马拉松跑者，强调挑战极限和运动社群归属',
    targetAudience: '15-35岁跑步新手、跑团成员、马拉松爱好者、运动风穿搭用户',
    brandTone: '专业、极致、挑战极限、年轻、潮流、充满动感，语气鼓励且燃',
    bannedWords: '冠军保证、永久不伤脚、最快、唯一、绝对提升成绩',
    suitableScenes: ['运动', '城市', '晨跑', '夜跑', '雨中', '训练', '挑战', '热血转场'],
    suitableFormats: ['short', 'drama-style', 'end-card'],
    budgetTier: 'high',
    assetVisualElements: ['Swoosh 标志', '赛事号牌', '终点线', '脚着地瞬间', '鞋底纹路', '城市天际线', '荧光绿/亮橙动感色'],
    usageScenarios: ['晨跑', '夜跑', '训练前热身', '雨中奔跑', '跑团集合', '城市挑战'],
    emotionalMapping: ['热血', '自律', '挑战', '释放', '社群归属'],
    cameraSuggestions: ['low angle tracking shot', 'foot strike macro', 'speed ramp', 'sweat detail close-up'],
    audioSuggestions: ['脚步声', '呼吸声', '城市低频', '节拍鼓点'],
    forbiddenRepresentations: ['不得保证冠军成绩', '不得承诺永久不伤脚', '不得声称绝对提升成绩'],
    formatFit: {
      short: '用脚步、城市、鞋底科技三镜头快速建立动感。',
      'drama-style': '用跑前犹豫到迈出第一步的小冲突完成情绪解决。',
      'end-card': '片尾以安静但有力量的跑步背影收束。',
    },
  },
  {
    id: 'auto-byd-new-energy',
    industry: '新能源汽车 / 智能制造',
    brandName: '比亚迪',
    productName: '新能源汽车全系',
    sourceMaterial: '素材来自 demo 广告素材库：新版 BYD LOGO，秦/宋/唐/汉/元等车系前脸与尾灯辨识造型，城市快速路、家庭自驾、公路穿越自然景观、充电桩、太阳能电站、储能系统、金属质感光效、三电技术与刀片电池结构示意。',
    keySellingPoint: '电池、电机、电控三电优势，刀片电池/DM-i 技术，高安全性、高效率、长续航和低用车成本',
    targetAudience: '25-45岁城市家庭、二胎家庭、初次购车年轻人、环保与科技偏好者、海外电动车用户',
    brandTone: '科技、可靠、领先、民族自豪感、务实中带未来感',
    bannedWords: '自动驾驶无风险、绝对安全、最强、零事故、世界第一',
    suitableScenes: ['城市', '公路', '家庭', '旅行', '科技', '能源', '通勤', '片尾'],
    suitableFormats: ['drama-style', 'end-card', 'short'],
    budgetTier: 'high',
    assetVisualElements: ['BYD LOGO', '车系前脸与尾灯', '城市快速路', '充电桩', '金属质感光效', '刀片电池结构示意', 'dashboard glow'],
    usageScenarios: ['城市通勤', '家庭自驾', '公路夜景', '周末旅行', '充电补能', '雨夜接送'],
    emotionalMapping: ['可靠', '科技感', '安全感', '未来感', '家庭安心'],
    cameraSuggestions: ['tracking shot', 'city night drive', 'dashboard glow', 'tail light match cut', 'wide road shot'],
    audioSuggestions: ['低频环境声', '城市夜景氛围', '车门关闭声', '轻微电流声'],
    forbiddenRepresentations: ['不得表现无人驾驶绝对安全', '不得承诺零事故', '不得夸大续航或世界第一'],
    formatFit: {
      'drama-style': '用雨夜接送/家庭出行小冲突，让车辆作为可靠解决方案自然介入。',
      'end-card': '片尾以前方道路和尾灯收束，克制露出品牌。',
      short: '用车灯、内饰、城市路面三镜头表现科技与可靠。',
    },
  },
  {
    id: 'travel-ctrip-package',
    industry: '在线旅游服务 / 旅游度假',
    brandName: '携程旅行',
    productName: '旅行套餐',
    sourceMaterial: '素材来自 demo 广告素材库：蓝色小海豚 LOGO、蓝白主色调、全球地标、机场/车站/登机口/酒店大堂、行李箱/护照/登机牌、家庭合照/朋友合影/情侣牵手背影、套餐项目图标、行程规划表和地图路线。',
    keySellingPoint: '机票、酒店、景点门票、接送一站式打包，资源丰富、价格优势、亲子/情侣/家庭/商旅等场景化套餐与服务保障',
    targetAudience: '亲子游家庭、情侣朋友组团、背包客、中高价值旅行用户、商旅与团队用户',
    brandTone: '可靠、专业、便捷、友好，带有说走就走的轻松感和旅行情绪价值',
    bannedWords: '最低价、唯一、包治愈、绝对无忧、免费',
    suitableScenes: ['旅行', '家庭', '情侣', '朋友', '机场', '酒店', '片尾', '慢节奏转场'],
    suitableFormats: ['end-card', 'buffer-card', 'drama-style', 'interactive'],
    budgetTier: 'medium',
    assetVisualElements: ['蓝色小海豚 LOGO', '蓝白主色调', '全球地标', '行李箱', '护照登机牌', '地图路线', '酒店大堂'],
    usageScenarios: ['片尾计划下一段旅行', '家庭亲子游', '情侣出行', '机场转场', '酒店入住', '朋友合影'],
    emotionalMapping: ['可靠', '便捷', '期待', '松弛', '说走就走'],
    cameraSuggestions: ['map route animation', 'airport tracking shot', 'luggage close-up', 'warm family wide shot'],
    audioSuggestions: ['登机提示音', '行李箱滚轮声', '轻快旅行音乐', '海风环境声'],
    forbiddenRepresentations: ['不得承诺最低价', '不得宣称绝对无忧', '不得表现治愈疾病或包治愈'],
    formatFit: {
      'end-card': '下一集前以行程卡和目的地氛围安静露出，避免强促销。',
      'buffer-card': '用地图路线/窗外风景做剧情转场呼吸点。',
      'drama-style': '用临时出行计划的小冲突，服务一站式解决。',
      interactive: '让用户选择下一段想去海边还是城市。',
    },
  },
]
